### PR TITLE
Pull request to get updates from ICRAR master

### PR DESCRIPTION
**Pull request by pelahi**
@rtobar has improved and addressed bugs in VR, particularly in relation to HDF5 and handling extra property data, along with some improved code re-useability.

### CODE REVIEW

**Comment by pelahi** [comment]
@rtobar is there any reason you removed a default constructor for the struct Options and just added initialisation to all variables in allvars.cxx (see https://github.com/ICRAR/VELOCIraptor-STF/blob/44c4960f73393927ec76d7cfc0a66ae94f257560/src/allvars.h#L417-L1044)

**Comment by rtobar** [comment]
> @rtobar is there any reason you removed a default constructor for the struct Options and just added initialisation to all variables in allvars.cxx (see https://github.com/ICRAR/VELOCIraptor-STF/blob/44c4960f73393927ec76d7cfc0a66ae94f257560/src/allvars.h#L417-L1044)

Yes, all details are in https://github.com/ICRAR/VELOCIraptor-STF/commit/8f380fcd4b53c4b1063eaa294e270e30610daf4b

Note that even though I removed the default constructor, the compiler still automatically generates one that performs member variable initialisation.

**Comment by pelahi** [comment]
Thanks for the information. 
What about the new files. I understand the compilation files and the exception stuff (which both seem to have single commits associated with them). Is there any reason to have a time class in the vr namespace other than moving the associated functions MyGetTime and MyElapsedTime in utils.cxx?

**Comment by rtobar** [comment]
> Thanks for the information. What about the new files. I understand the compilation files and the exception stuff (which both seem to have single commits associated with them). Is there any reason to have a time class in the vr namespace other than moving the associated functions MyGetTime and MyElapsedTime in utils.cxx?

Yes, the `timer` class is a simpler-to-use timing object. It not only replaces the `MyGetTime` and `MyElapsedTime`, but it also can be put into a `std::basic_ostream`, making it convenient to use when logging elapsed times.

Related to timing see also https://github.com/ICRAR/VELOCIraptor-STF/commit/9940c4f30534236b9993324dec349969c83297a2.

**Comment by pelahi** [comment]
Hi @rtobar , I have noticed the use of `HOST_NAME_MAX` in `main.cxx` (see for example https://github.com/ICRAR/VELOCIraptor-STF/blob/44c4960f73393927ec76d7cfc0a66ae94f257560/src/main.cxx#L61) 
I am not certain how portable this is. Certainly this variable is not defined on the mac os. Would `NAME_MAX` be an acceptable alternative?

**Comment by pelahi** [comment]
Hi @rcanasv , I am looking at these lines 
https://github.com/ICRAR/VELOCIraptor-STF/blob/44c4960f73393927ec76d7cfc0a66ae94f257560/src/localfield.cxx#L664-L691
and just want to understand what this is doing. Can you provide any comments?

**Comment by rtobar** [comment]
> Hi @rtobar , I have noticed the use of `HOST_NAME_MAX` in `main.cxx` (see for example https://github.com/ICRAR/VELOCIraptor-STF/blob/44c4960f73393927ec76d7cfc0a66ae94f257560/src/main.cxx#L61) I am not certain how portable this is. Certainly this variable is not defined on the mac os. Would `NAME_MAX` be an acceptable alternative?

Since we're not necessarily supporting Macs this has gone unnoticed. If you need to get this compiling on MacOS, whatever gives you a compilation is fine I guess -- you can even remove the faulty line from being compiled on MacOS. `HOST_NAME_MAX` is specified by POSIX thought, so maybe it's a matter of defining `_POXIS_C_SOURCE` or similar.

**Comment by pelahi** [comment]
@rtobar  do you mind providing comments on the set of updates to the hdf5 interface? There are few commits and I will go through them but a few comments on motivation and any thing you this is critical is quite useful.

**Comment by rtobar** [comment]
> @rtobar do you mind providing comments on the set of updates to the hdf5 interface? There are few commits and I will go through them but a few comments on motivation and any thing you this is critical is quite useful.

The main motivation that started the changes was https://github.com/ICRAR/VELOCIraptor-STF/issues/88 (writing datasets >2GB in parallel). While finding out what this was about I deep dived into the `H5OutputFile` class, and found it had some duplicated code, and some of its functions were over-specified, so I went and decided to clean those bits up before doing the actual change that allowed for >2GB dataset writing.

The PR with the full list of commits that were merged is https://github.com/ICRAR/VELOCIraptor-STF/pull/111. You can read each commit messages for more information on their individual rationale, but most of the more relevant commits are towards the end. After the PR was merged there were a few other commits to fix a couple of lingering issues that came after this refactoring, they should appear linked from https://github.com/ICRAR/VELOCIraptor-STF/issues/88 as well.

**Comment by pelahi** [comment]
Hi @rtobar, I have a request/question. I would like to just squash all the commits that are related to improving the HDF5 interface into a single commit and then cherry pick that commit/make a PR. My naive idea would be to create a branch on the icrar fork of `feature/hdf5-update` with these squashed commits, make a PR, resolve conflicts and merge. Just makes it easier to merge and also keep the commit history. But it does mean have a PR for a branch that is, once merged, deleted. Not ideal. Plus you'd have to add me as a contributor to the icrar fork. 

My other option is to simply do this manually but that is time consuming and doesn't retain the commit history. It has been what I have been doing to add loggging for instance. Although adding stuff manually has allowed me to understand the updates (and also spot occasional bugs), this isn't ideal either. 

With your git-fu, do you have a better suggestion?

**Comment by rtobar** [comment]
> Hi @rtobar, I have a request/question. I would like to just squash all the commits that are related to improving the HDF5 interface into a single commit and then cherry pick that commit/make a PR.
> 
> With your git-fu, do you have a better suggestion?

You can do that without the need to write to the ICRAR repo.

While standing on your local copy of your repo, create a new branch where you want to build up the commits, then you can  `git cherry-pick` the commits to copy them into your branch. Finally you can push that to your repo. The `git cherry-pick` command while guide you through conflicts, etc, so you can `--abort` and `--continue` as you go through the commits when there are conflicts.

In your case, the list of commits you want to cherry-pick is b3c3371..7126e6d, plus 9c4a07e, so you'd end up doing something like:

```sh
# in case you don't already have a remote for ICRAR's fork
git remote add icrar https://github.com/ICRAR/VELOCIraptor-STF
git fetch icrar

# create new branch off your current master (or from wherever you want to do it)
git checkout pelahi/master
git checkout -b hdf5-fixes-from-icrar

# Go, go, go!
git cherry-pick b3c3371..7126e6d
# if conflicts arise you'll be fixing them, etc, and cherry-pick --continue (or --abort to start anew)
git cherry-pick 9c4a07e

# Push to your repo, create PR if needed, etc
git push -u pelahi hdf5-fixes-from-icrar
```

**Comment by pelahi** [comment]
Hi @rtobar , so I've done as you suggested (with a minor change in that I rebased and cherry picked the rebase). Do you have an hdf5 input I could test, one with multiple extra fields I could load? I have some myself but keen to try a few.

**Comment by rtobar** [comment]
> Hi @rtobar , so I've done as you suggested (with a minor change in that I rebased and cherry picked the rebase). Do you have an hdf5 input I could test, one with multiple extra fields I could load? I have some myself but keen to try a few.

One of the last commits in that sequence added a new small test program that exercises the `H5OutputFile` class directly, so you can use that to verify that the class works as intended. The program doesn't require any input, it generates all in memory.

**Comment by pelahi** [comment]
Hi @rtobar , sorry for the delay. It has been quite trying getting time to do updates to VR. 
I noticed something odd but maybe I am just missing something. In the HDF5 updates, some routines return const (see https://github.com/ICRAR/VELOCIraptor-STF/blob/343f294f9af5126f2947fe8945ab707f4a2ba088/src/hdfitems.h#L234-L301). Why return const value? Wouldn't it make sense to return `const &T`?

**Comment by rtobar** [comment]
> In the HDF5 updates, some routines return const (see https://github.com/ICRAR/VELOCIraptor-STF/blob/343f294f9af5126f2947fe8945ab707f4a2ba088/src/hdfitems.h#L234-L301). Why return const value?

I don't think there's a need to return const here, I agree. According to git blame you wrote those functions, I haven't touched them, so if there was some historical reason it's unknown to me (but again, probably unnecessary).

> Wouldn't it make sense to return `const &T`?

Nope, you'd be referencing values created on the stack of those functions, which cease to exist once the function exits, and thus the references are invalid.

Returning `T` and `std::vector<T>` should be fine, the returned objects can be made const by the caller if required.

**Comment by pelahi** [comment]
Aha, so the culprit was me (likely copying/editing code by John Helly and compounding errors). I'll remove the const.

**Comment by pelahi** [comment]
Hi @rtobar , I've integrated almost all the changes that exist in the icrar master branch. I would like to test results to make sure all the computation is correct. Is there a particular set of colibre swift sims to use? What about the negative densities which was fixed by making sure particles are not included twice? Was there a particular snapshot that would be good to test? Thanks for any help.

**Comment by pelahi** [comment]
Oh, the branch which has these updates exist is `feature/codecleanup-icrar`

**Comment by MatthieuSchaller** [comment]
Sorry to jump in, but are all the "negative densities" occurrences really gone? I think some of the issues are still open on this front.

**Comment by rtobar** [comment]
@pelahi When you addressed the MPI-related problem that caused non-positive densities I copied some datasets to Pawsey for you to work with (I copied them under /tmp, then you put them somewhere else private for you). Those should work for testing purposes.

> Sorry to jump in, but are all the "negative densities" occurrences really gone? I think some of the issues are still open on this front.

@MatthieuSchaller no, they are not. There's still the OpenMP-related failure we haven't been able to properly identified, and that we're still tracking on https://github.com/ICRAR/VELOCIraptor-STF/issues/53. The fix that Pascal refers here is the MPI-related failure that caused non-positive densities.

**Comment by pelahi** [comment]
Hi @rtobar , @MatthieuSchaller  sorry for the delay in the following up. I just wanted to see if I could grab useful hydro and zoom input (been very busy with work so haven't had a chance till now). Also, should I try `/snap7/scratch/dp004/dc-borr1/new_randomness_runs/runs/Run_*` as outlined in https://github.com/ICRAR/VELOCIraptor-STF/issues/53. I do have access to cosma so just let me know where things are on cosma and what resources I can use and I'm keen to my updates.

**Comment by MatthieuSchaller** [comment]
The data you mention will likely have disappeared already as it was on a scratch disk. 

Let me come back to you with another zoom hydro setup.

**Pull request closed without merging**
